// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyxcgprrgskevczdbznx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eGNncHJyZ3NrZXZjemRiem54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NzExNzgsImV4cCI6MjA1OTU0NzE3OH0.T3m5HihWqEbaCBgHBdHhOaS7qBGBB9DDQNwWhPnn1Mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);